# Generated by Django 3.0.7 on 2020-07-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_auto_20200724_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(default='static/image/1.jpg', upload_to='static/image/'),
        ),
    ]
