# Generated by Django 3.0.7 on 2020-07-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_userinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/image/'),
        ),
    ]
